SELECT OWNER, TABLE_NAME
FROM ALL_TABLES
WHERE OWNER = 'DW_SCO'
  AND (TABLE_NAME LIKE '%MONODROG%' OR TABLE_NAME LIKE '%DROGA%'
       OR TABLE_NAME LIKE '%ACCION%' OR TABLE_NAME LIKE '%FARMACOL%')
ORDER BY TABLE_NAME
